- name: Add user 'bitpolII'
  user:
    name: bitpolII
    comment: Backup system user
    group: molgenis
  when: setup_backup|bool

- name: Create .ssh folder for bitpolII
  file:
     path: /home/bitpolII/.ssh
     state: directory
     owner: bitpolII
     group: molgenis
     mode: 0700
  when: setup_backup|bool

- name: Create public key file for bitpolII
  authorized_key:
    user: bitpolII
    state: present
    manage_dir: yes
    key: "{{ lookup('hashi_vault', 'secret=secret/ops/ssh/bitpolII:id_rsa.pub token={{ vault.token }} url=http://localhost:8200')}}"
  when: not ci|bool and setup_backup|bool

- name: Create authorized key file for bitpolII
  authorized_key:
    user: bitpolII
    state: present
    manage_dir: yes
    key: "{{ lookup('hashi_vault', 'secret=secret/ops/ssh/bitpolII:authorized_keys token={{ vault.token }} url=http://localhost:8200')}}"
  when: not ci|bool and setup_backup|bool

- name: Set permission to authorized_key file
  file:
    path: /home/bitpolII/.ssh/authorized_keys
    owner: bitpolII
    group: molgenis
    mode: 0600
  when: not ci|bool and setup_backup|bool

- name: Stop connection to Vault
  command: pkill kubectl -9
  delegate_to: localhost
  when: not ci|bool and setup_backup|bool