---
galaxy_info:
  author: Chris Gavin <chris@chrisgavin.me>
  description: An Ansible role for signing SSH host keys with a CA key.
  license: GPL
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - xenial

dependencies: []
