- name: Install supervisor and node_exporter
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - supervisor
    - node_exporter

- name: Enable service at boot
  service:
    name: node_exporter
    state: started
    enabled: yes