- name: Install HTTPD
  yum: 
    name: ['httpd', 'mod_ssl']
    state: installed

- name: Create certificate-directories for SSL
  file:
    path: /etc/pki/tls/certs/{{ inventory_hostname }}/
    state: directory

- name: Install SSL certs
  copy:
    content: "{{ lookup('hashi_vault', 'secret=secret/ops/certificate/ssl/wildcard/gcc.rug.nl:{{ item }} token=s.hulkolx63rGsVz45HjpOA351 url=http://localhost:8200')}}"  
    dest: "/etc/pki/tls/certs/{{ inventory_hostname }}/{{ item }}"
  with_items:
    - certificate.crt
    - private.key
    - serverchain.crt

- name: Copy SSL config file
  template: 
    src: options-ssl-httpd.j2 
    dest: /etc/httpd/conf.d/options-ssl-httpd.conf

- name: Delete default files in HTTPD conf.d directory
  file:
    state: absent
    path: /etc/httpd/conf.d/{{ item }}
  with_items:
    - autoindex.conf
    - README
    - userdir.conf
    - welcome.conf
    - ssl.conf

- name: Install HTTPD virtualhost configuration
  template: 
    src: opal.j2
    dest: /etc/httpd/conf.d/opal.conf

- name: Ensure HTTPD is running
  service:
   name: httpd
   state: started